import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CatalogComponent from "../components/Catalog";

export default function Catalog() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    This is the Catalog Page in Child App
                </h1>
                <h2>More changes</h2>

                <CatalogComponent />
            </main>
        </div>
    )
}
