import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Nav = dynamic(() => import('container/nav'));
const Footer = dynamic(() => import('container/footer'));

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Child App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Nav>This is the Nav Component in Child App</Nav>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to the Child App
                </h1>

            </main>

            <Footer />

        </div>
    )
}
