import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Clients</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Clients Micro frontend
                </h1>

                <Stack spacing={2} direction="row">
                    <Button variant="contained">Contained</Button>
                    <Button variant="outlined">Outlined</Button>
                </Stack>

            </main>

        </div>
    )
}
